name: Deploy and Build on EC2

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: 병합된 pull request 확인
      if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
      run: echo "Pull request가 병합되었습니다."

    - name: Copy Files to EC2
      if: success()  # Only run if the previous step is successful
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: .
        target: "/home/docker/"

    - name: SSH into EC2 and execute commands
      if: success()  # Only run if the previous step is successful
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/docker/
          chmod +x gradlew
          ./gradlew clean build --build-cache --daemon -x test
